name = "farovon-market-analysis"
main = "src/worker.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "farovon_cf_worker_jwt_secret_2026"
