'use strict';

/**
 * Готовая классификация ~180 должностей из более раннего анализа (экспорт
 * диалога с ИИ, ~2938 сотрудников на 2026-09-10 — см. память сессии
 * grading-industry-rework-plan.md). Для каждой должности взято МАЖОРИТАРНОЕ
 * значение функциональной группы (group — ключ из gradingService.GROUPS) и
 * уровня (level) среди всех сотрудников на этой должности в источнике;
 * sampleCount — сколько сотрудников стояло за этим выводом.
 *
 * Это ТОЛЬКО подсказка для комиссии на экране оценки (предзаполняет выбор
 * функциональной группы), НЕ готовая оценка — сами баллы по факторам
 * (1-5 за каждый вопрос анкеты) в источнике не было и предполагать их нельзя.
 *
 * groupConflict / levelConflict — по этой должности у разных сотрудников в
 * источнике встречались разные значения (например «Электрик» на одном
 * заводе 4-й уровень, на другом 5-й; «Оператор»/«Специалист»/«Координатор»
 * вообще меняют функциональную группу по месту посадки) — комиссии стоит
 * присмотреться к таким внимательнее, а не доверять подсказке вслепую.
 *
 * Покрывает ~172 из текущих ~255 уникальных должностей (остальные либо новые
 * с момента экспорта, либо переименованы) — не проблема, для не покрытых
 * подсказки просто не будет.
 */

const POSITION_HINTS = [
  { position: "Грузчик", group: "auxiliary", level: 6, sampleCount: 314, groupConflict: false, levelConflict: false },
  { position: "Вспомогательный работник", group: "auxiliary", level: 5, sampleCount: 197, groupConflict: false, levelConflict: false },
  { position: "Шеф повар", group: "auxiliary", level: 4, sampleCount: 8, groupConflict: false, levelConflict: false },
  { position: "Водитель грузового автомобиля", group: "auxiliary", level: 5, sampleCount: 17, groupConflict: false, levelConflict: false },
  { position: "Техничка", group: "auxiliary", level: 6, sampleCount: 114, groupConflict: false, levelConflict: true },
  { position: "Электросварщик", group: "production", level: 4, sampleCount: 76, groupConflict: true, levelConflict: false },
  { position: "Юрист", group: "aup", level: 4, sampleCount: 6, groupConflict: true, levelConflict: false },
  { position: "Ветеринарный врач", group: "production", level: 4, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Кладчик", group: "production", level: 6, sampleCount: 43, groupConflict: false, levelConflict: false },
  { position: "Координатор", group: "auxiliary", level: 4, sampleCount: 18, groupConflict: true, levelConflict: true },
  { position: "Логист", group: "auxiliary", level: 4, sampleCount: 29, groupConflict: false, levelConflict: false },
  { position: "Электрик", group: "auxiliary", level: 5, sampleCount: 34, groupConflict: false, levelConflict: true },
  { position: "Руководитель", group: "sales", level: 2, sampleCount: 28, groupConflict: true, levelConflict: true },
  { position: "Оператор", group: "production", level: 5, sampleCount: 90, groupConflict: true, levelConflict: true },
  { position: "Фасовщица", group: "production", level: 6, sampleCount: 123, groupConflict: false, levelConflict: false },
  { position: "Строитель", group: "production", level: 3, sampleCount: 40, groupConflict: true, levelConflict: true },
  { position: "Заведующий складом", group: "auxiliary", level: 4, sampleCount: 33, groupConflict: true, levelConflict: true },
  { position: "Специалист", group: "aup", level: 4, sampleCount: 55, groupConflict: true, levelConflict: true },
  { position: "Вакцинатор", group: "production", level: 5, sampleCount: 7, groupConflict: false, levelConflict: false },
  { position: "Охранник", group: "auxiliary", level: 5, sampleCount: 103, groupConflict: true, levelConflict: false },
  { position: "Кладовщик", group: "auxiliary", level: 4, sampleCount: 39, groupConflict: true, levelConflict: true },
  { position: "Бригадир смены", group: "production", level: 3, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Менеджер по продажам", group: "sales", level: 4, sampleCount: 64, groupConflict: false, levelConflict: false },
  { position: "Производственный бухгалтер", group: "aup", level: 4, sampleCount: 20, groupConflict: false, levelConflict: false },
  { position: "Водитель миксера", group: "auxiliary", level: 5, sampleCount: 28, groupConflict: false, levelConflict: false },
  { position: "Складчик-продавец", group: "sales", level: 5, sampleCount: 248, groupConflict: false, levelConflict: false },
  { position: "Снабженец", group: "auxiliary", level: 4, sampleCount: 11, groupConflict: true, levelConflict: false },
  { position: "Бухгалтер-реализатор", group: "aup", level: 4, sampleCount: 35, groupConflict: false, levelConflict: false },
  { position: "Мастер", group: "production", level: 5, sampleCount: 44, groupConflict: true, levelConflict: true },
  { position: "Маляр", group: "production", level: 5, sampleCount: 25, groupConflict: true, levelConflict: false },
  { position: "Водитель погрузчика", group: "auxiliary", level: 5, sampleCount: 18, groupConflict: true, levelConflict: false },
  { position: "Торговый представитель", group: "sales", level: 4, sampleCount: 51, groupConflict: false, levelConflict: false },
  { position: "Повар", group: "auxiliary", level: 5, sampleCount: 18, groupConflict: true, levelConflict: false },
  { position: "Кассир", group: "auxiliary", level: 4, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Бухгалтер", group: "aup", level: 4, sampleCount: 49, groupConflict: false, levelConflict: false },
  { position: "Инженер-проектировщик", group: "production", level: 2, sampleCount: 8, groupConflict: false, levelConflict: true },
  { position: "Сборщик яиц", group: "production", level: 6, sampleCount: 14, groupConflict: false, levelConflict: false },
  { position: "Бухгалтер-кассир", group: "auxiliary", level: 4, sampleCount: 6, groupConflict: false, levelConflict: false },
  { position: "Аппаратчик сушки и помола", group: "production", level: 5, sampleCount: 25, groupConflict: false, levelConflict: false },
  { position: "Водитель", group: "auxiliary", level: 5, sampleCount: 76, groupConflict: false, levelConflict: false },
  { position: "Водитель экспедитор", group: "auxiliary", level: 4, sampleCount: 27, groupConflict: true, levelConflict: true },
  { position: "Технолог", group: "production", level: 4, sampleCount: 10, groupConflict: false, levelConflict: false },
  { position: "Диспетчер", group: "auxiliary", level: 4, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "Пекарь", group: "production", level: 5, sampleCount: 6, groupConflict: true, levelConflict: true },
  { position: "Лаборант", group: "production", level: 5, sampleCount: 40, groupConflict: false, levelConflict: true },
  { position: "Упаковщик яиц", group: "production", level: 6, sampleCount: 16, groupConflict: false, levelConflict: false },
  { position: "Слесарь", group: "auxiliary", level: 5, sampleCount: 12, groupConflict: false, levelConflict: false },
  { position: "Жестянщик", group: "production", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Помощник оператора", group: "production", level: 5, sampleCount: 6, groupConflict: false, levelConflict: true },
  { position: "Помощник повара", group: "auxiliary", level: 6, sampleCount: 23, groupConflict: false, levelConflict: false },
  { position: "Птицевод", group: "production", level: 5, sampleCount: 27, groupConflict: false, levelConflict: true },
  { position: "Менеджер", group: "aup", level: 3, sampleCount: 8, groupConflict: true, levelConflict: true },
  { position: "Инженер ТБ", group: "auxiliary", level: 3, sampleCount: 7, groupConflict: true, levelConflict: true },
  { position: "Региональный руководитель", group: "sales", level: 3, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Машинист крана (Крановщик)", group: "production", level: 5, sampleCount: 7, groupConflict: true, levelConflict: false },
  { position: "Супервайзер", group: "sales", level: 3, sampleCount: 16, groupConflict: false, levelConflict: false },
  { position: "Водитель-продовец", group: "auxiliary", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Куратор", group: "auxiliary", level: 4, sampleCount: 2, groupConflict: true, levelConflict: true },
  { position: "Менеджер по трейд-маркетингу", group: "aup", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Садчик", group: "production", level: 6, sampleCount: 16, groupConflict: false, levelConflict: false },
  { position: "Старший оператор", group: "production", level: 4, sampleCount: 30, groupConflict: true, levelConflict: false },
  { position: "Инженер-строитель", group: "production", level: 4, sampleCount: 7, groupConflict: false, levelConflict: true },
  { position: "Лаборант-экспедитор", group: "production", level: 5, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Директор", group: "aup", level: 1, sampleCount: 6, groupConflict: true, levelConflict: true },
  { position: "Начальник смены", group: "production", level: 4, sampleCount: 10, groupConflict: false, levelConflict: true },
  { position: "Мойщик", group: "auxiliary", level: 6, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Шиномонтажник", group: "auxiliary", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Казначей", group: "aup", level: 3, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Стажер", group: "aup", level: 6, sampleCount: 20, groupConflict: true, levelConflict: true },
  { position: "Механик", group: "production", level: 4, sampleCount: 15, groupConflict: false, levelConflict: true },
  { position: "Старший лаборант", group: "production", level: 4, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Ветеринарно-санитарный врач", group: "production", level: 4, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "Директор департамента развития", group: "aup", level: 1, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Специалист по локациям и ассортименту", group: "production", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Кочегар", group: "auxiliary", level: 6, sampleCount: 8, groupConflict: true, levelConflict: false },
  { position: "Разнорабочий", group: "auxiliary", level: 6, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Заведующий лабораторией", group: "production", level: 3, sampleCount: 6, groupConflict: false, levelConflict: true },
  { position: "Садовник", group: "auxiliary", level: 6, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Начальник", group: "production", level: 3, sampleCount: 20, groupConflict: true, levelConflict: true },
  { position: "Начальник отдела", group: "aup", level: 3, sampleCount: 5, groupConflict: true, levelConflict: true },
  { position: "Помощник", group: "production", level: 4, sampleCount: 5, groupConflict: true, levelConflict: true },
  { position: "Слесарь-механик", group: "production", level: 5, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Региональный менеджер по рекламе", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Кассир-оператор", group: "aup", level: 4, sampleCount: 5, groupConflict: true, levelConflict: false },
  { position: "Системный администратор", group: "aup", level: 4, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Бригадир", group: "production", level: 3, sampleCount: 8, groupConflict: false, levelConflict: false },
  { position: "Председатель", group: "aup", level: 1, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Тракторист", group: "auxiliary", level: 5, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Младший бренд-менеджер", group: "aup", level: 5, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Экскаваторщик", group: "production", level: 4, sampleCount: 7, groupConflict: true, levelConflict: true },
  { position: "Старший бренд-менеджер", group: "aup", level: 3, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Начальник производства", group: "production", level: 2, sampleCount: 8, groupConflict: false, levelConflict: false },
  { position: "Оформитель", group: "auxiliary", level: 4, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Слесарь-ремонтник", group: "production", level: 5, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Бухгалтер-операционист", group: "auxiliary", level: 4, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Крановщик", group: "production", level: 5, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Автомойщик", group: "auxiliary", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Вальцерез", group: "production", level: 5, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Заведующий гаражом", group: "auxiliary", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Аудитор", group: "aup", level: 3, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Слесарь-монтажник", group: "production", level: 5, sampleCount: 5, groupConflict: false, levelConflict: true },
  { position: "Оператор плазморезного оборудование", group: "production", level: 4, sampleCount: 6, groupConflict: false, levelConflict: false },
  { position: "Начальник цеха", group: "production", level: 3, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Инженер ПТО", group: "production", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Инженер", group: "production", level: 5, sampleCount: 4, groupConflict: true, levelConflict: true },
  { position: "Экспедитор - грузчик", group: "auxiliary", level: 5, sampleCount: 6, groupConflict: false, levelConflict: false },
  { position: "Главный сварщик", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Оператор кательной", group: "production", level: 5, sampleCount: 11, groupConflict: false, levelConflict: true },
  { position: "Младший аудитор", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Главный механик", group: "production", level: 3, sampleCount: 7, groupConflict: false, levelConflict: false },
  { position: "Стажер по работе с локациями", group: "auxiliary", level: 5, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "HR BP", group: "aup", level: 4, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Монтажник СКС", group: "aup", level: 4, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "HR Generalist", group: "aup", level: 4, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "Заправщик", group: "auxiliary", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Специалист по работе с вендорами", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Старший специалист", group: "auxiliary", level: 4, sampleCount: 8, groupConflict: true, levelConflict: false },
  { position: "Расчетный бухгалтер", group: "aup", level: 4, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Специалист ОТК", group: "production", level: 4, sampleCount: 9, groupConflict: true, levelConflict: false },
  { position: "Инкасатор-водитель", group: "auxiliary", level: 5, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "Водитель электроавтотележки", group: "auxiliary", level: 6, sampleCount: 8, groupConflict: false, levelConflict: false },
  { position: "Кладовщик - доставщик", group: "auxiliary", level: 4, sampleCount: 3, groupConflict: false, levelConflict: false },
  { position: "Экономист", group: "aup", level: 4, sampleCount: 8, groupConflict: false, levelConflict: false },
  { position: "Методолог", group: "aup", level: 4, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "Главный инженер", group: "production", level: 3, sampleCount: 2, groupConflict: true, levelConflict: false },
  { position: "Весовщик", group: "production", level: 5, sampleCount: 4, groupConflict: false, levelConflict: true },
  { position: "Технический специалист", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Монтажник", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Сборщик", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Главный технолог", group: "production", level: 3, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Дизайнер", group: "aup", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Начальник котельной", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Методолог-аналитик", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Риск-менеджер", group: "sales", level: 3, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Главный энергетик", group: "auxiliary", level: 3, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Ведущий разработчик", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Переводчик", group: "auxiliary", level: 4, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "Бренд-менеджер", group: "aup", level: 4, sampleCount: 5, groupConflict: false, levelConflict: false },
  { position: "Разработчик", group: "aup", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Заместитель", group: "production", level: 3, sampleCount: 7, groupConflict: true, levelConflict: true },
  { position: "Медсестра", group: "auxiliary", level: 5, sampleCount: 4, groupConflict: false, levelConflict: true },
  { position: "Маркетинговый аналитик", group: "aup", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Заведующий хозяйством", group: "auxiliary", level: 4, sampleCount: 4, groupConflict: false, levelConflict: false },
  { position: "Сверловщик", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Администратор 1С", group: "aup", level: 3, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Ведущий специалист", group: "auxiliary", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Специалист по работе с локациями", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Менеджер по закупам", group: "sales", level: 4, sampleCount: 2, groupConflict: false, levelConflict: true },
  { position: "Руководитель направления маркетинга и работы с персоналом", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Специалист по операционному развитию", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Главный аудитор", group: "aup", level: 1, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Инженер-механик", group: "production", level: 5, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Старший системный администратор", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Оператор кислородной установки", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Senior HRBP", group: "aup", level: 3, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Мерчендайзер", group: "sales", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Инкубаторщик", group: "production", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Медбрат", group: "auxiliary", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Главный бухгалтер", group: "aup", level: 1, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Руководитель сектора по работе с ассортиментом продукции", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Врач", group: "auxiliary", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Моторист", group: "auxiliary", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Токарь-фрезеровщик", group: "production", level: 4, sampleCount: 2, groupConflict: false, levelConflict: false },
  { position: "Инженер по водоснабжению", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Архивариус", group: "auxiliary", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Помощник механика", group: "production", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Маркетолог", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Помощник технолога", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Зоотехник", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Инспектор по операционному контролю", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Руководитель аппарата Правления", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Стропольщик", group: "production", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Фермер", group: "auxiliary", level: 6, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Элеваторщик", group: "auxiliary", level: 5, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Специалист ИТ поддержки", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Графический дизайнер", group: "aup", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Специалист по локациям и представитель проекта в Душанбе и РРП", group: "production", level: 4, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Менеджер по проектам", group: "production", level: 2, sampleCount: 1, groupConflict: false, levelConflict: false },
  { position: "Руководитель по направлению привлечённых товаров", group: "sales", level: 3, sampleCount: 1, groupConflict: false, levelConflict: false },
];

module.exports = { POSITION_HINTS };
